image: python:3.8

stages:
  - test
  - deploy

variables:
  FLASK_ENV: "production"

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python -m pytest  # Replace this with your test command

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip python3-dev nginx
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - gunicorn --workers=4 --bind=0.0.0.0:5000 wsgi:app &
    - cp deploy/nginx.conf /etc/nginx/nginx.conf
    - service nginx restart
  environment:
    name: production
    url: http://your-domain.com  # Replace this with your actual domain
  only:
    - master  # Adjust branch name as needed
